- src/Adyen/Service/Payout.php
- src/Adyen/Service/ResourceModel/Payout/ThirdParty/StoreDetail.php
- tests/PayoutThirdPartyTest.php
Hi,
this pull request contain new class for the storeDetail resource on the Payout api
https://docs.adyen.com/developers/payout-manual#storedetailforathirdpartypayout
> Add storeDetail

- src/Adyen/HttpClient/CurlClient.php
Remove sensitive data from logging
authorisation with cse token
> Remove sensitive data from logging

- src/Adyen/Service/ResourceModel/Payout/ThirdParty/StoreDetailsAndSubmitThirdParty.php
- tests/PayoutThirdPartyTest.php
Remove unnecessary restrictions for storeDetailsAndSubmitThirdParty
storeDetailsAndSubmitThirdParty call
> Remove unnecessary restrictions for storeDetailsAndSubmitThirdParty

- composer.json
- src/Adyen/Util/Util.php
- tests/Util/UtilTest.php
Check for hexadecimal digits before packing
Calculating signature with valid/invalid hmac
> Check for hexadecimal digits before packing

- directory-lookup.html
Fixed invalid JSON string
Tested validity of the changes using - https://jsonlint.com/
> Fixed invalid JSON

- src/Adyen/Client.php
Added a method to set the directory lookup URL.
Using it with Barclay Card smart pay who self-host Adyen.
**Fixed issue**: n/a
> Added a method to set the directory lookup URL.

- src/Adyen/HttpClient/CurlClient.php
Fix Directory Lookup call
Executed all test successful
#57
> #57 Fix directoryLookup call

- src/Adyen/Client.php
- src/Adyen/HttpClient/CurlClient.php
Fixing DirectoryLookup for client
All test passed locally with test credentials
#57
> New release for fixing DirectoryLookup for client

- checkout-api.html
- checkout-sdk.html
- checkout-util.html
- payment.html
- using-library.html
Added Checkout to ghpages, slightly reworked using-library.html
> PW-421: Add Checkout to gh-pages

- src/Adyen/HttpClient/CurlClient.php
- tests/MockTest/CheckoutTest.php
- tests/MockTest/CheckoutUtilityTest.php
- tests/MockTest/PaymentTest.php
- tests/MockTest/TestCaseMock.php
- tests/Resources/Payment/authorise-success.json
- tests/Resources/Payment/invalid-merchant-account.json
Added tests for Authorise API:
- Happy flow (full card data not being logged)
- HandleCurlError
- HandleResultError
> PW-448 Added mocking to Authorise API

- checkout-sdk.html
Docs update to PaymentSession, Payments/Result.
> Github.io: Update setup/verify with new endpoint names

- src/Adyen/Client.php
- src/Adyen/Service/ResourceModel/Modification/AdjustAuthorisation.php
- src/Adyen/Service/ResourceModel/Modification/Cancel.php
- src/Adyen/Service/ResourceModel/Modification/CancelOrRefund.php
- src/Adyen/Service/ResourceModel/Modification/Capture.php
- src/Adyen/Service/ResourceModel/Modification/Refund.php
- src/Adyen/Service/ResourceModel/Payment/Authorise.php
- src/Adyen/Service/ResourceModel/Payment/Authorise3D.php
- src/Adyen/Service/ResourceModel/Payout/Confirm.php
- src/Adyen/Service/ResourceModel/Payout/Decline.php
- src/Adyen/Service/ResourceModel/Payout/StoreDetailsAndSubmit.php
- src/Adyen/Service/ResourceModel/Payout/Submit.php
- src/Adyen/Service/ResourceModel/Payout/ThirdParty/ConfirmThirdParty.php
- src/Adyen/Service/ResourceModel/Payout/ThirdParty/DeclineThirdParty.php
- src/Adyen/Service/ResourceModel/Payout/ThirdParty/StoreDetail.php
- src/Adyen/Service/ResourceModel/Payout/ThirdParty/StoreDetailsAndSubmitThirdParty.php
- src/Adyen/Service/ResourceModel/Payout/ThirdParty/SubmitThirdParty.php
- Add payment and payout separated versions
- Set Payment API version to 40
- Set Payout API version to 30
> PW-694 Update API_VERSION in the library and separate the payments and payouts versions

- README.md
Update readme with correct namespace
> PW-730 Update readme with correct namespace

- src/Adyen/Service/Payment.php
- src/Adyen/Service/ResourceModel/Payment/Authorise3DS2.php
Added authorise3ds2 consumer
authorisation with authorise3ds2 flow
> Added authorise3ds2 consumer

- src/Adyen/Client.php
Add boleto payment method support update version v41,
> Update checkout api version to v41

- src/Adyen/Client.php
Updated checkout api version to v41
> Merge from develop for new 1.6.1 release

- src/Adyen/Client.php
- src/Adyen/Config.php
- src/Adyen/HttpClient/CurlClient.php
Add support for http_proxy in client
> Add support for http_proxy in the client

- .travis.yml
Add PHP 7.3 to travis.
n/a
**Fixed issue**
n/a
> Test PHP 7.3 with travis

- .gitignore
- src/Adyen/AdyenException.php
- src/Adyen/HttpClient/CurlClient.php
Just an enhancement of `AdyenException` by adding the `pspRefence` if it is set.
None
**Fixed issue**
None
> Add pspReference to AdyenException

- src/Adyen/Client.php
> update marketpay account from v4 to v5

- src/Adyen/Client.php
- tests/TestCase.php
Bump version to 3.0.0
Update checkout api version from 41 to 49
> PW-1442 Update adyen-php-api-library to checkout v49

- src/Adyen/Client.php
- src/Adyen/HttpClient/CurlClient.php
- src/Adyen/Service/BinLookup.php
- src/Adyen/Service/PosPayment.php
- src/Adyen/Service/ResourceModel/BinLookup/Get3dsAvailability.php
- src/Adyen/Service/ResourceModel/Modification/RefundWithData.php
> Release 3.0.0

- composer.json
- src/Adyen/Client.php
- src/Adyen/Util/Currency.php
- src/Adyen/Util/HmacSignature.php
- src/Adyen/Util/Sha256Signature.php
- src/Adyen/Util/Util.php
- tests/Adyen/Util/CurrencyTest.php
- tests/Adyen/Util/HmacSignatureTest.php
- tests/Adyen/Util/Sha256SignatureTest.php
Split Util\Util in classes with specific concerns (#122)
Deprecating Util\Util class, Please use these classes instead:
- Adyen\Util\Currency
- Adyen\Util\HmacSignature
- Adyen\Util\Sha256Signature
> Release 4.0.0

- src/Adyen/Client.php
- src/Adyen/HttpClient/CurlClient.php
- src/Adyen/Service/AbstractResource.php
- src/Adyen/Service/Checkout.php
- src/Adyen/Service/Modification.php
- src/Adyen/Service/Payment.php
- src/Adyen/Util/Uuid.php
- tests/CheckoutTest.php
- tests/Util/UuidTest.php
> [PW-1673] add support for idempotency

- src/Adyen/Client.php
- src/Adyen/HttpClient/CurlClient.php
- src/Adyen/Service/AbstractResource.php
- src/Adyen/Service/Checkout.php
- src/Adyen/Service/Modification.php
- src/Adyen/Service/Payment.php
- src/Adyen/Util/Uuid.php
- tests/CheckoutTest.php
- tests/Util/UuidTest.php
* [PW-1673] add support for idempotency
* Update src/Adyen/HttpClient/CurlClient.php
Co-Authored-By: cyattilakiss <42297201+cyattilakiss@users.noreply.github.com>
* Update to 4.1.0
> [PW-1673] add support for idempotency (#124)

- src/Adyen/HttpClient/CurlClient.php
Accept 2xx and 3xx status code response. This aims to handle 202 status code not as error.
Account creation
#127
> Add 2xx and 3xx response code as valid status codes

- phpunit.xml
Add the copyright ASCII and change the list of files read.
> Change PHPUnit configuration

- src/Adyen/Config.php
I think 'return' is not allowed in constructor
> remove return in construct

- .gitignore
- .travis.yml
- CONTRIBUTING.md
- README.md
- composer.lock
- src/Adyen/Client.php
- src/Adyen/Config.php
Added New contribution guidelines
#134 Add composer.lock 
#139 PW-1904 Upgrade checkout API endpoint from v49 to v51
> Release 5.0.0

- src/Adyen/Client.php
Update Notification endpoint version.
`v1` version doesn't seem to be saving the `eventConfigs`
> update notification endpoint version

- src/Adyen/Client.php
- src/Adyen/Service/ResourceModel/BinLookup/GetCostEstimate.php
**Fixed issue**:  Change monolog requirement for conflict with Laravel #173
> Release 6.0.1

- src/Adyen/HttpClient/CurlClient.php
Add accepted http status codes 201, 202 and 204 in requestJson()
Adyen API can respond with 200, 201, 202 and 204 http codes when OK
#176
> [PW-2231] Throwing AdyenException for successful response

- src/Adyen/Client.php
- src/Adyen/Service/DisputeService.php
- src/Adyen/Service/ResourceModel/DisputeService/DefendDispute.php
- src/Adyen/Service/ResourceModel/DisputeService/DeleteDisputeDefenseDocument.php
- src/Adyen/Service/ResourceModel/DisputeService/RetrieveApplicableDefenseReasons.php
- src/Adyen/Service/ResourceModel/DisputeService/SupplyDefenseDocument.php
Integration for `/DisputeService` service resources. Related documentation: https://docs.adyen.com/risk-management/disputes-api/disputes-api-reference#endpoints
> Integration for /DisputeService service resources

- .gitattributes
- remove useless files for production from package
- configure git to automatic line endings normalized
packagist ignore configured files and remove them from distribution
**Fixed issue**: none
> added .gitattributes to remove useless files for production from package

- .github/workflows/main.yml
- sonar-project.properties
- src/Adyen/HttpClient/CurlClient.php
- src/Adyen/Service/BinLookup.php
- src/Adyen/Service/DisputeService.php
- src/Adyen/Service/ResourceModel/BinLookup/GetCostEstimate.php
- src/Adyen/Service/ResourceModel/DisputeService/DefendDispute.php
- src/Adyen/Service/ResourceModel/DisputeService/DeleteDisputeDefenseDocument.php
- src/Adyen/Service/ResourceModel/DisputeService/RetrieveApplicableDefenseReasons.php
- src/Adyen/Service/ResourceModel/DisputeService/SupplyDefenseDocument.php
- tests/Unit/AbstractResourceTest.php
With the objective of migrating our CI to GitHub Actions, this commit introduces a first step.
GitHub Actions running on every push and pull request
> Create a GitHub Actions workflow

- src/Adyen/Service/Validator/CheckoutStateDataValidator.php
- src/Adyen/Service/Validator/DataArrayValidator.php
- tests/Integration/ValidatorTest.php
The generic way of implementation of the checkout components includes sending all the data from the component to the API endpoint. Since this data is coming from the frontend we should validate them otherwise the request can be changed a lot.
Unit test the getArrayOnlyWithApprovedKeys function
> [PW-2266] Add request validator for the payments call

- src/Adyen/Service/Validator/CheckoutStateDataValidator.php
Add 'paymentData' and 'details' into $stateDataRootKeys so the state data from the action components can be validated as well
> Add 'paymentData' and 'details' into $stateDataRootKeys

- .github/dependabot.yml
- composer.json
- composer.lock
- src/Adyen/Client.php
- src/Adyen/Service/Checkout.php
- src/Adyen/Service/ResourceModel/Checkout/PaymentLinks.php
- src/Adyen/Service/Validator/CheckoutStateDataValidator.php
- tests/Resources/Checkout/payment-links-invalid.json
- tests/Resources/Checkout/payment-links-success.json
- tests/Unit/CheckoutTest.php
#208 Add integration for paymentLinks under checkout API
#212 Create Dependabot config file
#214 Add 'paymentData' and 'details' into $stateDataRootKeys
> Release 7.1.0

- README.md
Add timeout option configuration to remind developers to avoid request hang
> Add timeout option configuration

- composer.json
- composer.lock
- tests/Integration/Builder/AddressTest.php
- tests/Integration/Builder/BrowserTest.php
- tests/Integration/Builder/CustomerTest.php
- tests/Integration/Builder/OpenInvoiceTest.php
New version of PHPCS introduces new sniffs that needs fixing.
None, code style changes only.
> Fix code style for new version of PHPCS

- README.md
- src/Adyen/Client.php
- src/Adyen/Service/Builder/Referral.php
- src/Adyen/Service/ResourceModel/RiskManagement/SubmitReferrals.php
- src/Adyen/Service/RiskManagement.php
- tests/Integration/Builder/ReferralTest.php
- tests/Resources/RiskManagement/submitReferralsWithData-success.json
- tests/Unit/RiskManagementTest.php
This fixes some issues in #234 that were created when merging #225 to develop.
**Fixed issue**:   #233 #234
> Add referrals api support

- .github/CODEOWNERS
PR created to add myself to the codeowners.
> Add myself to the codeowners

- src/Adyen/Util/IpAddress.php
Handle getAdyenIpAddresses hostname cannot be resolved case
> Handle gethostbynamel bool return

- src/Adyen/Client.php
The update introduces breaking changes and would be released as a major release.
This PR updates the version of [checkout API](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/overview)
The related release notes can be found here: https://docs.adyen.com/online-payments/release-notes#checkout-api-v67 
**Fixes issues:**
#258 Checkout API v67 Support
> Update checkout api version to v67

- README.md
- composer.json
- composer.lock
- src/Adyen/Client.php
- src/Adyen/Util/IpAddress.php
- tests/Integration/CheckoutTest.php
- tests/Resources/Checkout/payments-success.json
- tests/Unit/CheckoutTest.php
#259 Update checkout api version to v67 
#260 Handle gethostbynamel bool return 
#261 Update readme 
**Important note:**
The release introduces breaking changes.
The version of [checkout API](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/overview) is updated to v67
The related API release notes can be found here: https://docs.adyen.com/online-payments/release-notes#checkout-api-v67 
**Fixes issues:**
Fixes #258 Checkout API v67 Support
> Release 10.0.0

- composer.json
- composer.lock
- src/Adyen/Client.php
- src/Adyen/Service/Hop.php
- src/Adyen/Service/ResourceModel/Hop/GetOnboardingUrl.php
- src/Adyen/Service/ResourceModel/Hop/GetPciQuestionnaireUrl.php
- tests/Resources/Hop/invalid-return-url.json
- tests/Resources/Hop/url-failure.json
- tests/Resources/Hop/url-success.json
- tests/Unit/HopTest.php
#266  Add HOP resources
**Fixed issue**:  Resolves #271
> Release 10.1.0

- composer.json
Update license information in composer
**Fixed issue**: resolves #274
> Update license in composer.json

- src/Adyen/Service/Recurring.php
- src/Adyen/Service/ResourceModel/Recurring/NotifyShopper.php
- tests/Resources/Recurring/notifyShopper-success.json
- tests/Unit/RecurringTest.php
> [PW-4468] Add new endpoint /notifyShopper

- .gitignore
- based on https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/generic-php/gitignore.example
- from bottom up grouping
- anchor directories
- exclude ignored `test.ini.sample`
What do you think?
> Structured gitignore file

- composer.json
- composer.lock
Fix Monolog version constraints
Happy Composer :)
**Fixed issue**
#283
> Fix Monolog version constraints

- src/Adyen/Client.php
Reduce complexity.
**Fixed issue**
Make it viktor-brain compatible 🧠 
1. Errors go into conditionals
2. Normal operations are not indented/wrapped in conditionals
> Make Client constructor more readable

- .github/workflows/main.yml
Full throttle please!
**Related issue**
#283
> Strict Composer validation in CI

- .github/workflows/main.yml
> Run SonarCloud check only with its token available

- README.md
Add missing information about live url prefix.
> Update lib usage for live environment in README.md

- src/Adyen/Service/Account.php
- src/Adyen/Service/ResourceModel/Account/CheckAccountHolder.php
Make [Account checkAccountHolder](https://docs.adyen.com/api-explorer/#/Account/v6/post/checkAccountHolder) endpoint accessible from this library
> Implement checkAccountHolder ressource for Account service

- .github/CODEOWNERS
- .github/workflows/main.yml
- README.md
- composer.json
- composer.lock
- src/Adyen/Client.php
- src/Adyen/HttpClient/ClientInterface.php
- src/Adyen/HttpClient/CurlClient.php
- src/Adyen/Service/AbstractResource.php
- src/Adyen/Service/Checkout.php
- src/Adyen/Service/Management.php
- src/Adyen/Service/ResourceModel/Checkout/Refunds.php
- src/Adyen/Service/ResourceModel/Checkout/Reversals.php
- src/Adyen/Service/ResourceModel/Management/CompanyAccount.php
- src/Adyen/Service/ResourceModel/Management/CompanyWebhooks.php
- src/Adyen/Service/ResourceModel/Management/Me.php
- src/Adyen/Service/ResourceModel/Management/MerchantAccount.php
- src/Adyen/Service/ResourceModel/Management/MerchantClientKey.php
- src/Adyen/Service/ResourceModel/Management/MerchantWebhooks.php
- src/Adyen/Util/ManualCapture.php
- tests/Integration/CheckoutTest.php
- tests/Integration/ManagementTest.php
- tests/Resources/Account/create-account-success.json
- tests/Resources/AccountHolder/create-account-holder-success.json
- tests/Unit/AccountHolderTest.php
- tests/Unit/Util/ManualCaptureTest.php
Features
- #331 
- #328
- #342
- #329
Fixes
- #326
> Release 12.0.0

- .github/CODEOWNERS
- .github/workflows/main.yml
- README.md
- composer.json
- composer.lock
- src/Adyen/Client.php
- src/Adyen/HttpClient/ClientInterface.php
- src/Adyen/HttpClient/CurlClient.php
- src/Adyen/Service/AbstractResource.php
- src/Adyen/Service/Checkout.php
- src/Adyen/Service/Management.php
- src/Adyen/Service/ResourceModel/Checkout/Refunds.php
- src/Adyen/Service/ResourceModel/Checkout/Reversals.php
- src/Adyen/Service/ResourceModel/Management/CompanyAccount.php
- src/Adyen/Service/ResourceModel/Management/CompanyWebhooks.php
- src/Adyen/Service/ResourceModel/Management/Me.php
- src/Adyen/Service/ResourceModel/Management/MerchantAccount.php
- src/Adyen/Service/ResourceModel/Management/MerchantClientKey.php
- src/Adyen/Service/ResourceModel/Management/MerchantWebhooks.php
- src/Adyen/Util/ManualCapture.php
- tests/Integration/CheckoutTest.php
- tests/Integration/ManagementTest.php
- tests/Resources/Account/create-account-success.json
- tests/Resources/AccountHolder/create-account-holder-success.json
- tests/Unit/AccountHolderTest.php
- tests/Unit/Util/ManualCaptureTest.php
Brings version 12.0.0 commits to `main` branch.
> Release 12.0.0 history

- src/Adyen/HttpClient/ClientInterface.php
- src/Adyen/HttpClient/CurlClient.php
- src/Adyen/Service/ResourceModel/Management/MerchantWebhooks.php
- tests/Integration/ManagementTest.php
Added support for PATCH request in curl client
Added method for [webhook update](https://docs.adyen.com/api-explorer/#/ManagementService/v1/patch/merchants/{merchantId}/webhooks/{webhookId}) API endpoint
- Creating new webhook ✅
- Updating webhook ✅
> Add patch request to curl client

- src/Adyen/HttpClient/ClientInterface.php
- src/Adyen/HttpClient/CurlClient.php
- src/Adyen/Service/ResourceModel/Management/MerchantWebhooks.php
- tests/Integration/ManagementTest.php
**Features**
Add patch request for management API update webhooks call (#353)
> Release 12.1.0

- src/Adyen/Service/Management.php
- src/Adyen/Service/ResourceModel/Management/AllowedOrigins.php
- tests/Integration/ManagementTest.php
Add the following endpoints 
- `get` /me/allowedOrigins
- `post` /me/allowedOrigins
Add related unit tests
> [PW-6509] Add allowed origins endpoint for the management api

- Vagrantfile
- src/Adyen/Service/Builder/OpenInvoice.php
Optional `imageUrl` and `productUrl` parameters added to the open invoice line item builder.
Vagrant file was also upgraded in order to work with Parallels.
> [PW-6861] - Add image and product url parameters to the open invoice line item builder

- src/Adyen/Service/AbstractResource.php
- src/Adyen/Service/NotificationReceiver.php
- src/Adyen/Util/HmacSignature.php
- src/Adyen/Util/OpenInvoice.php
From #289
@AlexandrosMor I will never tell anyone about this 🙊
> Fix boolean handling

- README.md
- composer.json
- composer.lock
- src/Adyen/Client.php
- src/Adyen/Service/AbstractResource.php
- src/Adyen/Service/Builder/OpenInvoice.php
- src/Adyen/Service/NotificationReceiver.php
- src/Adyen/Util/HmacSignature.php
- src/Adyen/Util/OpenInvoice.php
- tests/Integration/Builder/OpenInvoiceTest.php
**Fixes**
- #396
- #388
**Others**
- #385
- #392
- #398
> Release 13.0.2

- README.md
- src/Adyen/Client.php
- src/Adyen/Region.php
- src/Adyen/Service/PosPayment.php
> Release 13.0.3

- src/Adyen/Service/Checkout.php
- src/Adyen/Service/ResourceModel/Checkout/TechnicalCancels.php
- tests/Integration/CheckoutTest.php
See the description in #406 
Integration tests are skipped from my local environment and nothing in the docs indicates how to configure them.
Resolves #406
> [Checkout] Add checkout technical cancels

- src/Adyen/Client.php
- src/Adyen/Region.php
List of the valid regions updated.
> Fix for region validation & add India to the regions list

- README.md
- composer.json
- composer.lock
- src/Adyen/Client.php
- src/Adyen/Region.php
- src/Adyen/Service/Checkout.php
- src/Adyen/Service/ResourceModel/Checkout/TechnicalCancels.php
- tests/Integration/CheckoutTest.php
- #408 
- #402 
- #404 
- #409
> Release 13.0.4

- .github/workflows/main.yml
We use this lib with PHP 8.1/8.2, it should be tested against that.
> Test against newest PHP versions

- .github/workflows/models.yml
- .github/workflows/services.yml
- Makefile
This PR adds automated generation pipeline for models and services.
> [ITT-450] Add service and model generation pipeline

- src/Adyen/Service/BinLookup.php
- src/Adyen/Service/Checkout.php
- src/Adyen/Service/CheckoutUtility.php
- src/Adyen/Service/Management.php
- src/Adyen/Service/Modification.php
- src/Adyen/Service/Payment.php
- src/Adyen/Service/Payout.php
- src/Adyen/Service/Recurring.php
This PR adds a deprecation tag to the constructor of the old services that got a new model based replacement.
> Deprecate old services

- README.md
- src/Adyen/Client.php
This PR changes the banner and prepares the release.
> Finalising for release

- README.md
Add feedback section to README
> Add feedback section to README

- README.md
Minor change: updated the list of required extensions in README.md
> Update list of required PHP extensions in README.md

- Makefile
Remove Capital from Makefile.
This should fix the service generation Pipeline.
> Remove Capital from Makefile

- .github/workflows/gh_release.yml
- .github/workflows/main.yml
- .github/workflows/release_request.yml
- Makefile
These workflows assist us on publishing new releases.  I'm also simplifying the build matrix.
> ITT-537: Add release automation

- .github/workflows/release_request.yml
Add input flag to make a pre-release on manual runs.
> Pre-release input flag

- src/Adyen/Service/RiskManagement.php
Let's keep supporting this endpoint since there is no better replacement for it yet. 
Fixes #570
> Maintain support for Risk Management

- README.md
Updates the badge to our Packagist page.
> Link to Packagist

- .github/workflows/gh_release.yml
We update the version to 2.0.0 but this release automation is not working properly
> Revert release automation version to 1.1.1

- src/Adyen/Util/HmacSignature.php
Updated doc block for isHmacSupportedEventCode method in HmacSignature class to improve static code analysis.
N.a.
**Fixed issue**:  N.a.
> Updated isHmacSupportedEventCode  docblock

- .github/workflows/codeql-analysis.yml
- renovate.json
This PR adds codeQL analysis workflow.
> Create codeql analysis workflow

- README.md
Shields.io can display the current version.
One less thing to change during release.
@DjoykeAbyah
> Make Packagist badge automatic

- templates/api-single.mustache
- templates/api.mustache
- templates/model_generic.mustache
> Fix deprecation info - remove extra new line

- .github/workflows/label_new_issues.yml
- .github/workflows/main.yml
- .github/workflows/stale.yml
Fix vulnerability by setting the permissions  in the workflows
> Vulnerability fix: set workflow permissions

- .github/workflows/release.yml
Upgrade to release-automation-action v1.4.0
> Update to release-automation-action v1.4.0

- .github/workflows/format.yml
Update to format any branch starting with `sdk-automation/` (i.e. `sdk-automation/PaymentsAPIs`)
> Format running on multiple branches

- .github/workflows/format.yml
Update filter to run on multiple branches
> Update filter in format.yml
