- src/Adyen/HttpClient/CurlClient.php
I wanted to extend the CurlClient of Adyen to add some custom functionality to the HTTP client. 
I created my own CurlClient class which extends Adyens' CurlClient. I only wanted to add some small pieces of code, so I want to reuse as much as possible. Currently the methods handleCurlError and handleResultError are private. 
I want to suggest to make them protected so they can be inherited.
Issue #12 would be even better, but hasn't been resolved yet and I don't have enough time to do that.
> Made error handlers protected instead of private

- .travis.yml
Title speaks for itself, I saw the nightly option which currently tests for PHP 7.2.0, but I think it's better to also test 7.0 and 7.1.
> Also testing php 7.0 and 7.1

- src/Adyen/Service/ResourceModel/Recurring/ListRecurringDetails.php
Contract is not required anymore so you can retrieve ONECLICK and RECURRING contracts in one call.
Tested with all test cases
#40
> #40 remove recurring.contract as required field

- src/Adyen/HttpClient/CurlClient.php
Only did a little bit code cleaning.
> Removed unnecessary code snippets.

- src/Adyen/AdyenException.php
The payment API is responding at times to a string instead of number, this is breaking the standard PHP exception.
> forces code always a integer :muscle:

- src/Adyen/Service/Modification.php
- src/Adyen/Service/ResourceModel/Modification/AdjustAuthorisation.php
- tests/ModificationTest.php
I wanted to use the API call for `adjustAuthorisation` in v30.
So I added the modification method in the php library. 
I created two tests in `ModificationTest.php` that increases and decreases the previously authorised amount.
> Add adjustAuthorisation to modification models

- src/Adyen/Client.php
- src/Adyen/Config.php
- src/Adyen/ConfigInterface.php
- src/Adyen/HttpClient/CurlClient.php
- src/Adyen/Service/ResourceModel/Payment/TerminalCloudAPI.php
Added timeout optional configuration, to be used on Magento2 terminal API.
Removed required fields relative to the payment, since we use the same endpoint for Status call as well.
> PW-458: Added timeout optional configuration

- src/Adyen/Service/AbstractResource.php
- src/Adyen/Service/ResourceModel/Checkout/PaymentMethods.php
- src/Adyen/Service/ResourceModel/Checkout/PaymentSession.php
- src/Adyen/Service/ResourceModel/Checkout/Payments.php
- src/Adyen/Service/ResourceModel/Checkout/PaymentsDetails.php
- src/Adyen/Service/ResourceModel/Checkout/PaymentsResult.php
- src/Adyen/Service/ResourceModel/CheckoutUtility/OriginKeys.php
- src/Adyen/Service/ResourceModel/DirectoryLookup/Directory.php
- src/Adyen/Service/ResourceModel/Modification/AdjustAuthorisation.php
- src/Adyen/Service/ResourceModel/Modification/Cancel.php
- src/Adyen/Service/ResourceModel/Modification/CancelOrRefund.php
- src/Adyen/Service/ResourceModel/Modification/Capture.php
- src/Adyen/Service/ResourceModel/Modification/Refund.php
- src/Adyen/Service/ResourceModel/Payment/Authorise.php
- src/Adyen/Service/ResourceModel/Payment/Authorise3D.php
- src/Adyen/Service/ResourceModel/Payment/TerminalCloudAPI.php
- src/Adyen/Service/ResourceModel/Payout/Confirm.php
- src/Adyen/Service/ResourceModel/Payout/Decline.php
- src/Adyen/Service/ResourceModel/Payout/StoreDetailsAndSubmit.php
- src/Adyen/Service/ResourceModel/Payout/Submit.php
- src/Adyen/Service/ResourceModel/Payout/ThirdParty/ConfirmThirdParty.php
- src/Adyen/Service/ResourceModel/Payout/ThirdParty/DeclineThirdParty.php
- src/Adyen/Service/ResourceModel/Payout/ThirdParty/StoreDetail.php
- src/Adyen/Service/ResourceModel/Payout/ThirdParty/StoreDetailsAndSubmitThirdParty.php
- src/Adyen/Service/ResourceModel/Payout/ThirdParty/SubmitThirdParty.php
- src/Adyen/Service/ResourceModel/Recurring/Disable.php
- src/Adyen/Service/ResourceModel/Recurring/ListRecurringDetails.php
- tests/CreatePaymentRequestTest.php
- tests/ExceptionTest.php
- tests/MockTest/CheckoutTest.php
Removed required fields, validate function and related tests
> PW-445: Removed required fields, validate function and related tests

- src/Adyen/Client.php
- src/Adyen/Service/AbstractCheckoutResource.php
- src/Adyen/Service/Checkout.php
- src/Adyen/Service/ResourceModel/Checkout/PaymentMethods.php
- src/Adyen/Service/ResourceModel/Checkout/PaymentSession.php
- src/Adyen/Service/ResourceModel/Checkout/Payments.php
- src/Adyen/Service/ResourceModel/Checkout/PaymentsDetails.php
- src/Adyen/Service/ResourceModel/Checkout/PaymentsResult.php
- src/Adyen/Service/ResourceModel/CheckoutUtility/OriginKeys.php
- tests/MockTest/CheckoutTest.php
PW-645 use dynamic identifier for live if provided, not provided throw error for checkout service as this is mandatory
Added checkout live test for this.
> PW-645 use dynamic identifier for live endpoint

- src/Adyen/Client.php
- tests/TestCase.php
- tests/config/test.ini
Add new setting to the config/tests.ini where it can be set if you are
working on the api library standalone on local
When this setting is set true then the missing defaults that can cause
issues are being set
> fix local unit test running caused by the missing date_default_timezone_set

- src/Adyen/Client.php
- tests/CheckoutTest.php
- tests/TestCase.php
v40 has some useful features that we need. A separate test case was added to verify the behaviour.
Tested the behavior with and without `blockedPaymentMethods` to verify that v40 is used.
> Update checkout API version to v40

- src/Adyen/Util/Util.php
- tests/ExceptionTest.php
- tests/Util/UtilTest.php
added formatAmount function and test
fix ExceptionTest
> PW-1520: added formatAmount function and test

- composer.json
- tests/MockTest/PaymentTest.php
- tests/MockTest/PosPaymentTest.php
Monolog has [released v2.0.0](https://github.com/Seldaek/monolog/releases/tag/2.0.0), but the Adyen PHP library blocks upgrading to this version.
Because Monolog 2.0.0 requires at least PHP 7.2, the version constraint for this library can't just be upped to v2, because that would drop support for PHP5.3
With the `>=1.16` users have the possibility of choosing the version of Monolog which suits them
> Allow the library to be used with Monolog 2

- src/Adyen/AdyenException.php
Description
So that Static Analysis tools like PHPStan/Psalm work properly with files that make use of this class.
Tested scenarios
Although I couldn't find any uses of the additional constructor arguments, the only changes in this PR are PHPDocs used by tools mentioned above
Fixed issue:
> Fixed PHPDoc for AdyenException

- src/Adyen/Client.php
The Fund API version is still set to use the v3 version, so I update this constant to be able to use the v5 fund API
> Update API_FUND_VERSION from v3 to v5

- .gitignore
- composer.lock
This standardizes the versions of libraries used.
> Add composer.lock

- src/Adyen/Client.php
Bump API_CHECKOUT_VERSION from v49 to v51
Important note:
Multibanco response changes from Received to PrestnToShopper
Example response from v49
```
{
"additionalData": {
"comprafacil.deadline": "1",
"comprafacil.reference": "111 111 1111",
"paymentMethod": "multibanco",
"refusalReasonRaw": "Setup performed successfully",
"comprafacil.entity": "11111",
"merchantReference": "0001",
"comprafacil.amount": "10.00",
"acquirerCode": "***",
"acquirerReference": "111 111 111"
},
"pspReference": "***",
"resultCode": "Received",
"merchantReference": "0001"
}
```
Example response from v51:
```
{
"resultCode": "PresentToShopper",
"action": {
"expiresAt": "2019-12-12T12:55:25",
"initialAmount": {
"currency": "EUR",
"value": 1000
},
"merchantName": "****",
"merchantReference": "0001", …
```
> PW-1904 Upgrade checkout API endpoint from v49 to v51

- src/Adyen/Client.php
- src/Adyen/Config.php
- src/Adyen/ConfigInterface.php
- src/Adyen/Service/AbstractResource.php
- src/Adyen/Service/ResourceModel/Payment/TerminalCloudAPI.php
- tests/PosPaymentTest.php
- tests/Unit/AbstractResourceTest.php
Add applicationInfo for terminal API requests inside SaleToAcquirerData.
If SaleToAcquirerData is empty, just add ApplicationInfo and base64encode it.
If SaleToAcquirerData contains data, add ApplicationInfo to it.
1. SaleToAcquirerData empty -> SaleToAcquirerData contains ApplicationInfo in base64
2. SaleToAcquirerData contains recurring details in querystring form -> SaleToAcquirerData contains recurring details and ApplicationInfo in Base64
3. SaleToAcquirerData contains recurring details in Base64 -> SaleToAcquirerData contains recurring details and ApplicationInfo in Base64
> PW-1188: Add applicationInfo into terminal API requests

- src/Adyen/Client.php
- src/Adyen/Config.php
- src/Adyen/ConfigInterface.php
- src/Adyen/Service/AbstractResource.php
- src/Adyen/Service/ResourceModel/Payment/TerminalCloudAPI.php
- tests/PosPaymentTest.php
- tests/Unit/AbstractResourceTest.php
* PW-1188 Add applicationInfo into terminal API requests
* PW-1188: add e2e tests
* PW-1188 add unittests, remove printlines from e2e tests
* PW-1188 more defensive in case SaleToAcquirerData is not defined
* fix comment on unittest
* PW-1188: add merchantApplication field to applicationInfo, add it to POS e2e test
* PW-1188 refactor
* Update src/Adyen/Service/AbstractResource.php
Co-Authored-By: Marcos Garcia <marcos.asgarcia@gmail.com>
* PW-1188 refactor
* fix using the right parameter for $allowApplicationInfo and deprecate interface as deprecated so we can remove it in future releases to cleanup the config object.
Co-authored-by: Marcos Garcia <marcos.asgarcia@gmail.com>
Co-authored-by: Rik ter Beek <rikterbeek@users.noreply.github.com>
**Fixed …
> Release 5.0.1

- src/Adyen/Client.php
Argument `$liveEndpointUrlPrefix` has a wrong PHPDoc type hint `null`, whereas `string|null` is expected in the code.
**Fixed issue**:  Static analysis tools, such as PHPStan or Phan, rely on PHPDoc and fail due to wrong type hint.
> Fix bad phpdoc typehint for $liveEndpointUrlPrefix argument

- Vagrantfile
- bin/composer-installer.sh
This automates the `vagrant up` command by provisioning required packages and dependencies, and installing them on a provisioning run.
The `bin/composer-installer.sh` file is a recommended automation found in getcomposer.org. It downloads the sha-key for validation from the GitHub repository and downloads the composer.phar from the main location. This ensures a more secure download.
> Improve Vagrant setup

- .travis.yml
PHP 7.4 was released in December. This change raises awareness on compatibility issues.
> Add PHP 7.4 to Continuous Integration

- Vagrantfile
The /vagrant folder is write-protected in CentOS. This configuration prevents PHPStorm of trying to access it to run tests or other configuration.
> Disable the default vagrant folder

- src/Adyen/Config.php
- src/Adyen/HttpClient/CurlClient.php
- tests/MockTest/PaymentTest.php
- tests/MockTest/TestCaseMock.php
Mask the encrypted card details and other sensitive data from the logs of the payments requests and responses if the environment is live
> [PW-2059] Mask encrypted/sensitive data in the logs

- composer.json
Revert monolog dependency change to >=1.16
**Fixed issue**:  #173
> Change monolog requirement for conflict with Laravel, fixes #173

- src/Adyen/Client.php
- src/Adyen/HttpClient/CurlClient.php
- src/Adyen/Service/DisputeService.php
- src/Adyen/Service/ResourceModel/DisputeService/DefendDispute.php
- src/Adyen/Service/ResourceModel/DisputeService/DeleteDisputeDefenseDocument.php
- src/Adyen/Service/ResourceModel/DisputeService/RetrieveApplicableDefenseReasons.php
- src/Adyen/Service/ResourceModel/DisputeService/SupplyDefenseDocument.php
#177 [PW-2231] Add accepted http status codes 201, 202 and 204 in requestJson() 
#151 integration for /DisputeService service resources
#176 Throwing AdyenException for successful response
> Release 6.1.0

- composer.json
this folder is already mapped by PSR-4, classmap is useless
autoloading continue to load files from `src/Adyen/Service/`
**Fixed issue**:  none
> remove duplicated classmap

- src/Adyen/Client.php
fix types declaration and return types in `\Adyen\Client` for:
- $config
- $httpClient
- $logger
and relative getters/setters
none
**Fixed issue**:  none
> fix client types declarations

- .github/workflows/main.yml
- sonar-project.properties
PHPUnit generates the Clover coverage files with absolute file paths, and I couldn't find a way to change that. So, instead, I set up a step in the Continuous Integration workflow to clean up the report files after it runs.
Code Coverage in SonarCloud with a short-lived branch.
> Add Code Coverage metrics to SonarCloud

- .gitattributes
- .github/workflows/main.yml
- README.md
- SECURITY.md
- composer.json
- composer.lock
- sonar-project.properties
- src/Adyen/Client.php
- src/Adyen/HttpClient/CurlClient.php
- src/Adyen/Service/BinLookup.php
- src/Adyen/Service/DisputeService.php
- src/Adyen/Service/ResourceModel/BinLookup/GetCostEstimate.php
- src/Adyen/Service/ResourceModel/DisputeService/DefendDispute.php
- src/Adyen/Service/ResourceModel/DisputeService/DeleteDisputeDefenseDocument.php
- src/Adyen/Service/ResourceModel/DisputeService/RetrieveApplicableDefenseReasons.php
- src/Adyen/Service/ResourceModel/DisputeService/SupplyDefenseDocument.php
- src/Adyen/Util/IpAddress.php
- tests/Unit/AbstractResourceTest.php
- tests/Unit/CheckoutTest.php
- tests/Unit/NotificationTest.php
- tests/Unit/PaymentTest.php
- tests/Unit/TestCaseMock.php
- tests/Unit/Util/IpAddressTest.php
With this release the library supports PHP version 5.3 and above for production environments but php 7.3 and above for development.
#194 Create a GitHub Actions workflow 
#193 Adyen IP validation function
#189 fix config typehint 
#186 fix client types declarations 
#185 remove duplicated classmap 
#184 added .gitattributes to remove useless files for production from package 
#182 Update composer.lock 
**Dependencies update**
#191 Update dependency phpunit/phpunit to v9.1.4 
#190 Update dependency phpunit/phpunit to v9.1.2 
#187 Update dependency squizlabs/php_codesniffer to v3.5.5 
#180 Update dependency phpunit/phpunit to v9.1.1 
#179 Update dependency phpunit/phpunit to v9.0.2
> Release 6.2.0

- src/Adyen/Util/HmacSignature.php
- tests/Unit/Util/HmacSignatureTest.php
Added the check isHmacSupportedEventCode to the library. This check returns true if the notification event code supports hmac calculation.
Add Unit test to test an existing event code in the list
> [PW-2385] Add check notification event code supports hmac.

- .travis.yml
- README.md
- composer.json
- composer.lock
PHP 5.3 is old and unmaintained and unsecure. PHP 5.6 offers some quality of life improvements, like traits and short array syntax.
> [PW-2381] Drop support for PHP 5.3, 5.4 and 5.5

- src/Adyen/Service/Checkout.php
- src/Adyen/Service/ResourceModel/Checkout/PaymentLinks.php
- tests/Resources/Checkout/payment-links-invalid.json
- tests/Resources/Checkout/payment-links-success.json
- tests/Unit/CheckoutTest.php
Integration for `/paymentLinks` endpoint in Checkout service, in order to support programmatically creating a Pay By link URL as per https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v52/post/paymentLinks
> Add integration for paymentLinks under checkout API

- src/Adyen/Client.php
- tests/Integration/CheckoutTest.php
- tests/Integration/CreatePaymentRequestTest.php
Bump API_CHECKOUT_VERSION from v52 to v64
Important note
The update will break some implementations because fo the following new features of the new API version therefore when releasing this update a new major version needs to be released of the library.
- Returns an error if unsupported fields (fields that are currently not in our API specifications) are provided in the payment request.
- Pending is now the response type instead of PresentToShopper for both bcmc_mobile_QR and wechatpayQR
- Added the configuration object to the /paymentMethods response for the API. Example can be found here: https://docs.adyen.com/api-explorer/#/CheckoutService/v64/post/paymentMethods__example_paymentMethods-basic (Click run to get the example response)
- Now returns an error when …
> [PW-2982] Upgrade checkout API endpoint from v52 to v64

- src/Adyen/AdyenException.php
- src/Adyen/HttpClient/CurlClient.php
- tests/Integration/ExceptionTest.php
When an AdyenException was thrown (after a curl call to the Adyen API) in src/Adyen/HttpClient/CurlClient.php's handleResultError() method, the error code, returned from the API-Response, was not properly passed.
It was casted to an int and thus sometimes truncated.
**Fixed issue**:240
> make full adyen error code accessible in AdyenException

- src/Adyen/Service/Builder/OpenInvoice.php
- tests/Integration/Builder/OpenInvoiceTest.php
- tests/Integration/ExceptionTest.php
Remove unsupported itemId from open invoice builder since in the checkout API version 64 it's not supported anymore
> Remove unsupported itemId from open invoice builder

- .github/workflows/main.yml
- src/Adyen/Service/NotificationReceiver.php
Bugfix in `validateNotificationMode`, if `$notificationMode` is passed as a string 'false' and `$testMode` is `false` then logic fails
> [PW-2843] bug fix in check for notificationMode as string

- .github/workflows/main.yml
- src/Adyen/Client.php
This PR updates the version of [checkout API](https://docs.adyen.com/api-explorer/#/CheckoutService/v66/overview)
The update introduces breaking changes and would be released as a major release.
- All `shopperReference` values that are less than 3 characters long will now trigger a validation error.
- Merchants are no longer able to send a mix of both the `storePaymentMethod: true` and `enableRecurring`, `enableOneClick` fields in the same `/payments` request. A validation error will be thrown.
- The `paid` field in the `/paymentLinks` response now returns `completed` instead of `paid`
See other added features in [release notes](https://docs.adyen.com/online-payments/release-notes#nov-30th-2020)
> [PW-3779] update checkout API version

- .github/CODEOWNERS
- composer.json
- composer.lock
- src/Adyen/Client.php
- src/Adyen/Service/Builder/OpenInvoice.php
- src/Adyen/Util/OpenInvoice.php
- tests/Integration/Builder/OpenInvoiceTest.php
- tests/Integration/ExceptionTest.php
- tests/Unit/Util/OpenInvoiceTest.php
#245 Add Affirm and Clearpay as open invoice payment methods
#249 bug fix in check for notificationMode as string
#252 Update dependency phpunit/phpunit to v9.5.1
#254 Update checkout API version from v64 to v66
**Important note**
This update will bump the version of checkout API used and will introduce the following breaking changes.
- All `shopperReference` values that are less than 3 characters long will now trigger a validation error.
- Merchants are no longer able to send a mix of both the `storePaymentMethod: true` and `enableRecurring`, `enableOneClick` fields in the same `/payments` request. A validation error will be thrown.
- The `paid` field in the `/paymentLinks` response now returns `completed` instead of `paid`
See other added features in [release …
> Release 9.0.0

- src/Adyen/AdyenException.php
- src/Adyen/HttpClient/CurlClient.php
Revert breaking change in 8.1.0
Keep `errorCode()` the same for backwards compatibility
**Fixed issue**: Resolves #250
> Keep error code the same for backwards compatibility

- src/Adyen/Util/ManualCapture.php
- tests/Unit/Util/ManualCaptureTest.php
The payment methods that supports AUTH flow are also supporting manual capture. The list with the payment methods is added in the library so we have one method to update and to not duplicate the list across the platforms, 
Added a unit test for the payment methods variants
> [PW-6283] Add manual capture payment methods list

- src/Adyen/Service/AbstractResource.php
- src/Adyen/Service/Checkout.php
- src/Adyen/Service/ResourceModel/Checkout/Refunds.php
- src/Adyen/Service/ResourceModel/Checkout/Reversals.php
- tests/Integration/CheckoutTest.php
Added path parameters handler that allows implementing the rest methods of the Checkout API integration.
Added `v68` Checkout methods implementation:
- POST [/payments/{paymentPspReference}/refunds](https://docs.adyen.com/api-explorer/#/CheckoutService/v68/post/payments/{paymentPspReference}/refunds)
- POST [/payments/{paymentPspReference}/reversals](https://docs.adyen.com/api-explorer/#/CheckoutService/v68/post/payments/{paymentPspReference}/reversals)
Both methods have integration test:
- \Adyen\Tests\Integration\CheckoutTest::testRefunds
- \Adyen\Tests\Integration\CheckoutTest::testReversals
> V68 implementation: refunds + reversals

- src/Adyen/HttpClient/CurlClient.php
- src/Adyen/Service/ResourceModel/Management/AllowedOrigins.php
- src/Adyen/Service/ResourceModel/Management/CompanyAccount.php
- src/Adyen/Service/ResourceModel/Management/MerchantAccount.php
- tests/Integration/ManagementTest.php
Add to /merchants endpoint call query params using an associative array
- Query parameters that could be used 
1. `pageNumber` 
The number of the page to fetch.
2. `pageSize` 
The number of items to have on a page, maximum 100. The default is 10 items on a page
End to end test added for pageSize
> [PW-6598] Add query parameters to get merchant call

- src/Adyen/Service/ResourceModel/Management/MerchantWebhooks.php
- tests/Integration/ManagementTest.php
Add test and get list endpoints for webhook merchants account
To test properly the webhook configuration we need to add the `/test` endpoint and pass the `merhcantAccount` with the `webhookId`. For details please check the [docs](https://docs.adyen.com/api-explorer/#/ManagementService/v1/post/merchants/{id}/webhooks/{webhookId}/test) 
Endpoints added: 
- `https://management-test.adyen.com/v1/merchants/{id}/webhooks/{webhookId}/test`
- `https://docs.adyen.com/api-explorer/#/ManagementService/v1/get/merchants/{id}/webhooks`
- 
Get all the merchants endpoints
It is not possible to use the test endpoint by creating a unit test
> [PW-6531]Add /test and /list endpoints for webhooks

- src/Adyen/Service/DirectoryLookup.php
With Directory Lookup, you can fetch the available payment methods from Adyen. However it is reaching the end of life so it is marked as `deprecated` so we prevent new merchants to use it. 
It is only annotation so the tests should pass. No new tests added
> [PW-4648] Add deprecated annotation for directory lookup function

- src/Adyen/Config.php
#381 mentioned correctly that our config constructor will not properly set null array for older than php8.
> Add Array type in config constructor function for old php versions

- src/Adyen/Service/Builder/OpenInvoice.php
- tests/Integration/Builder/OpenInvoiceTest.php
Update buildOpenInvoiceLineItem method according to [Checkout API v69](https://docs.adyen.com/api-explorer/#/CheckoutService/v69/post/payments).
- `amountIncludingTax` and `itemCategory` parameters added.
- `taxCategory` parameter removed.
> [PW-7020] - Update buildOpenInvoiceLineItem method according to Checkout API v69

- src/Adyen/Client.php
- src/Adyen/Region.php
- src/Adyen/Service/PosPayment.php
- src/Adyen/Service/ResourceModel/Payment/TerminalCloudAPI.php
`setRegion()` method is defined in the `Client` class to set the region of the call.
This method expects `us`,`au` or `eu` as an input. Then, in the `PosPayment` class constructor, terminal api endpoint is overridden with the help this parameter if it is set.
> [PW-7170] - Add region based endpoints for terminal api

- src/Adyen/Util/ManualCapture.php
Added googlepay subvariants, applepay cartesbancaires and new walley variants in manualCapture payment methods list
**Fixed issue**:  #PW-7706 #PW-8003 #PW-7706
> Added missing variants to manual capture list

- README.md
- src/Adyen/Client.php
- src/Adyen/Service/AbstractResource.php
Checkout API paymentLinks endpoint fails due to wrong endpoint URL.
- paymentLinks endpoint fixed.
- Management API endpoint updated to follow same convenience
> (Hotfix Main)[ITT-433] Fix paymentLinks endpoint URL builder

- README.md
- src/Adyen/Client.php
- src/Adyen/Config.php
- src/Adyen/HttpClient/CurlClient.php
Added support for setting a custom certificate path in the Curl Client.
This is needed in our scenario when proxying Adyen requests through [VGS](https://www.verygoodsecurity.com/docs/guides/outbound-connection#tls-certificates) for PCI compliance.
In addition in this MR, if a proxy URL contains the scheme, the proposed change will keep it in the final URL that gets set into `CURLOPT_PROXY`. By stripping it, some proxies (VGS included) are not connecting properly.
> Add support for custom certificate in the Curl Client

- src/Adyen/Service/AbstractResource.php
When doing the same call twice, the old updated endpoint is stored in an instance variable which cause issues.
```php
$checkout = new Checkout();
$result = $checkout->paymentMethods(/** args */);
// later ...
$result = $checkout->paymentMethods(/** other args */);
```
This last call will always use the same args as the first call because of how the path parameters are being updated and stored.
**Fixed issue**:  N/A
> Fix multiple calls on same method with same instance

- src/Adyen/Service/AbstractResource.php
If a `saleToAcquirer` object has a set a definite characters in it in a given order in base64 encoded string, PHP's in-built `parse_str()` function considers it as a query parameter array, which results in faulty modification of the original `saleToAcquirer` data. If the object is broken, POS payment attempt is rejected by terminal api with `Reason: Failed validation` error message.
In this PR, the order of the condition changed to first check if the `saleToAcquirer` data is a base64 encoded string.
> Fix POS SaleToAcquirerData base64 encoding

- src/Adyen/Service/Account.php
- src/Adyen/Service/BinLookup.php
- src/Adyen/Service/Checkout.php
- src/Adyen/Service/CheckoutUtility.php
- src/Adyen/Service/DisputeService.php
- src/Adyen/Service/Fund.php
- src/Adyen/Service/Hop.php
- src/Adyen/Service/Management.php
- src/Adyen/Service/Modification.php
- src/Adyen/Service/Notification.php
- src/Adyen/Service/Payment.php
- src/Adyen/Service/Payout.php
- src/Adyen/Service/Recurring.php
- src/Adyen/Service/RiskManagement.php
move deprecation annotations to class level so more IDE's will handle and show deprecation correctly.
> move deprecation annotations to class level

- src/Adyen/Service/Builder/Address.php
- src/Adyen/Service/Builder/Browser.php
- src/Adyen/Service/PosPayment.php
While working on previous PR-s I've found these.
> Fix dockblocks

- CONTRIBUTING.md
- README.md
We don't use `develop` branch anymore.
> Update contributing guide

- templates/model_generic.mustache
This fixes the default setting of bools (and removes the need for nullable bools as bools are not serialised by default unless explicitly set). Fixes: #593 #601 
Verified by regenerating checkout and parsing the bools to json. Automation will pick it up.
> Remove default setting of bool

- src/Adyen/Service/ResourceModel/Checkout/Cancels.php
- src/Adyen/Service/ResourceModel/Checkout/Captures.php
- src/Adyen/Service/ResourceModel/Checkout/Refunds.php
- src/Adyen/Service/ResourceModel/Checkout/Reversals.php
This PR sets the `allowApplicationInfo` field to `true` for modification request calls from plugin same as for /payments calls, with the aim of providing data on **cancel**, **capture**, **refund** and **reversal** calls in the plugin allowing more visibility on such data and possible tracking.
Cancel, Refund, Capture
> [ECP-9272] Allow Application Info in request parameters for modifications 

- .github/workflows/stale.yml
updated stale.yml to ignore pull requests.
- unset the default checks by setting them to -1
- only consider pr's with the labels  'awaiting-changes', 'blocked', 'work-in-progress', 'awaiting-upstream'.
- removing the pr label when updated
> update stale .yml

- src/Adyen/Util/HmacSignature.php
- tests/Unit/Util/HmacSignatureTest.php
- Deprecated old Hmac validation method 
- updated unit test with new validateHMACSignature method.
Tested by running the unit tests
> deprecated old HmacSignature method, adjusted unittest

- tests/Unit/Util/HmacSignatureTest.php
Created a test case `testMerchantReferenceWithSpace` to ensure the correct HMAC is calculated when the merchantReference contains spaces. This test checks both the recalculated HMAC and the validation.
> added test for merchantReference with space

- src/Adyen/Client.php
- src/Adyen/Region.php
- tests/Unit/RegionTest.php
Added APSE to valid regions since we have a live endpoint added to TERMINAL_API_ENDPOINTS_MAPPING
> added APSE to VALID_REGIONS

- tests/TestCase.php
Fix for actual endpoint using retrieveCloudEndpoint instead of hard coded endpoint string
> fix assert for testGetCloudEndpointForTestEnvironment

- templates/api-single.mustache
- templates/api.mustache
- templates/model_generic.mustache
This PR improves the mustache templates by adding the additional information (`deprecationInVersion`, `deprecationMessage`) to deprecated models and services. The info is displayed only when at least`x-deprecatedInVersion` is available. Else, only the deprecation tag is displayed.
- Ran the adyen-sdk-automation against the adyen-php-library to verify expected output.
Before:
```
* @deprecated
```
After:
```
* @deprecated  since Configuration API v2. "Please use `bankAccount` object instead"
```
> Add deprecation info

- templates/api.mustache
This PR fixes the mustache templates by adding the additional information (`deprecationInVersion`, `deprecationMessage`) to deprecated `services`. The info is displayed only when at least`x-deprecatedInVersion` is available. Else, only the deprecation tag is displayed.
Relates to PR #735 
- Ran the `adyen-sdk-automation` against the `adyen-php-library` to verify expected output.
> Add deprecation info for services

- src/Adyen/Client.php
- src/Adyen/Config.php
- src/Adyen/HttpClient/CurlClient.php
- tests/Unit/TestCaseMock.php
This PR add a new configuration for HTTP client to set `CURLOPT_CONNECTTIMEOUT` and defines default values for `CURLOPT_CONNECTTIMEOUT` and `CURLOPT_TIMEOUT` settings of the client.
- Polling `/paymentMethods` endpoint with different network settings vs client configurations
> [DR-1284] Add CURLOPT_CONNECTTIMEOUT setting and define default values for timeouts

- src/Adyen/Util/HmacSignature.php
- tools/hmac/HMACValidator.php
- tools/hmac/HMACValidatorBanking.php
- tools/hmac/HMACValidatorPayments.php
- tools/hmac/README.md
- tools/hmac/payload.json
- tools/hmac/payload2.json
Add scripts in `tools/hmac` to troubleshoot the HMAC signature computation of the PHP library
> HMAC Troubleshooting tool

- templates/model.mustache
Update Mustache template to remove `@description` as it is not a valid PhpDoc annotation.
The code must be re-generated once this PR is merged.
Fix #757
> Remove invalid PHPDoc tag @description

- src/Adyen/Service.php
- tests/Resources/PosMobileApp/create-auth-session.json
- tests/Unit/ClientTest.php
- tests/Unit/PosMobileApiTest.php
- tests/Unit/ServiceTest.php
Correct `Live` URL for PosSdk (PosMobileApi).
Fix #759
> Correct PosSdk (PosMobileService) LIVE url

- src/Adyen/AdyenException.php
Mark explicitly parameters with a null default as `?Type` if they are typed.
Fix #768
> Fix warning: Implicitly marking parameter $params as nullable is deprecated

- tests/Resources/BalancePlatform/get-account-holder-additional-attributes.json
- tests/Resources/BalancePlatform/get-account-holder-unknown-enum.json
- tests/Resources/BalancePlatform/get-account-holder.json
- tests/Unit/AccountHolderTest.php
- tests/Unit/BalancePlatformTest.php
Adding unit tests to verify:
- additional response attributes don't thrown an exception
- unknown response enums don't thrown an exception: this fails. Test is skipped until the enum parsing will be corrected
> Add tests for unknown enums and attributes

- templates/model.mustache
Fix templates to remove leading backslash
```
use \ArrayAccess;
```
to
```
use ArrayAccess;
```
> Remove leading backslash

- src/Adyen/Service/BankingWebhookParser.php
- tests/Unit/NotificationTest.php
Remove custom check that was necessary for AcsWebhook `RelayedAuthenticationRequest`.
The webhook schema provides now the attribute `type` with the event code necessary for the deserialization.
Test has been updated accordingly.
> AcsWebhooks: remove custom fix
